micronaut:
  application:
    name: pet-service
  http:
    services:
      identity-service:
        url: "http://identity-service"

datasources:
  default:
    db-type: postgres # required for flyway to run with JDBC driver

r2dbc:
  datasources:
    default:
      dialect: postgres
      options:
        currentSchema: pet_service

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - db/migrations
      default-schema: ${r2dbc.datasources.default.options.currentSchema}