micronaut:
  http:
    services:
      identity-service:
        url: "http://localhost:8080"
  security:
    oauth2:
      clients:
        keycloak:
          openid:
            issuer: 'http://keycloak.local:8082/realms/petclinic'
  server:
    port: 8083

dev:
  postgres:
    url: postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

datasources:
  default:
    url: jdbc:${dev.postgres.url}
    username: ${dev.postgres.username}
    password: ${dev.postgres.password}

r2dbc:
  datasources:
    default:
      url: r2dbc:${dev.postgres.url}
      username: ${dev.postgres.username}
      password: ${dev.postgres.password}

kafka:
  bootstrap:
    servers: localhost:9092
