micronaut:
  application:
    name: pet-service
  http:
    services:
      identity-service:
        url: "http://identity-service"
  security:
    intercept-url-map:
      - pattern: /api/**
        access:
          - isAuthenticated()
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-id: '${micronaut.application.name}'
          client-secret: '${OAUTH2_CLIENT_SECRET:changeme}'
    token:
      propagation:
        enabled: true
        service-id-regex: "identity-service"
      cookie:
        cookie-name: "JWT"
  data:
    pageable:
      default-page-size: 10

datasources:
  default:
    db-type: postgres # required for flyway to run with JDBC driver

r2dbc:
  datasources:
    default:
      dialect: postgres
      options:
        currentSchema: ${micronaut.application.name}

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - db/migrations
      default-schema: ${r2dbc.datasources.default.options.currentSchema}

redis:
  caches:
    pet-owner:
      charset: UTF-8

app:
  ports:
    output:
      pet-owner:
        required-identity-role-name: "PET_OWNER"