micronaut:
  server:
    port: 8083

dev:
  postgres:
    url: postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

datasources:
  default:
    url: jdbc:${dev.postgres.url}
    username: ${dev.postgres.username}
    password: ${dev.postgres.password}

r2dbc:
  datasources:
    default:
      url: r2dbc:${dev.postgres.url}
      username: ${dev.postgres.username}
      password: ${dev.postgres.password}


