micronaut:
  application:
    name: identity-service

jpa:
  default:
    entity-scan:
      packages:
        - tech.aaregall.lab.micronaut.petclinic.identity.infrastructure
    properties:
      hibernate:
        hbm2ddl.auto: update

datasources:
  default:
    driver-class-name: org.postgresql.Driver