micronaut:
  application:
    name: identity-service
  security:
    intercept-url-map:
      - pattern: /api/**
        access:
          - isAuthenticated()
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-id: '${micronaut.application.name}'
          client-secret: '${OAUTH2_CLIENT_SECRET:changeme}'

jpa:
  default:
    entity-scan:
      packages:
        - tech.aaregall.lab.micronaut.petclinic.identity.infrastructure
    properties:
      hibernate:
        hbm2ddl.auto: update

datasources:
  default:
    driver-class-name: org.postgresql.Driver