micronaut:
  application:
    name: vet-service

  http:
    services:
      identity-service:
        url: "http://identity-service"

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    schema: ${micronaut.application.name}

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - db/migrations
      default-schema: ${datasources.default.schema}

app:
  ports:
    output:
      vet-id-validation:
        required-identity-role-name: "VET"