micronaut:
  application:
    name: vet-service
  http:
    services:
      identity-service:
        url: "http://identity-service"
  security:
    intercept-url-map:
      - pattern: /api/**
        access:
          - isAuthenticated()
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-id: '${micronaut.application.name}'
          client-secret: '${OAUTH2_CLIENT_SECRET:changeme}'
    token:
      propagation:
        enabled: true
        service-id-regex: "identity-service"

datasources:
  default:
    db-type: postgres
    driver-class-name: org.postgresql.Driver
    schema: ${micronaut.application.name}

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - db/migrations
      default-schema: ${datasources.default.schema}

app:
  ports:
    output:
      vet-id-validation:
        required-identity-role-name: "VET"