name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Run build with Gradle Wrapper
        run: ./gradlew build